// Handcrafted starter layouts for the Roomcraft demo.
//
// These are plain data, not AI output. Each layout matches the SceneLayout
// shape validated by the Roomcraft add-on: positions are object origins in
// scene-local meters, X is right, Y is up, and positive Z faces the viewer.
// Rotation is an upright Y-axis angle in radians and scale multiplies the
// catalog asset's physical size or the authored part geometry.
//
// A catalog object names an asset, while a compound object lists parts
// instead and is built from primitives at load time.

/** A warm seating group that reads well from the default preview viewpoint. */
export const READING_NOOK = {
  title: 'Reading nook',
  objects: [
    {
      id: 'nook-sofa',
      asset: 'sofa',
      name: 'Terracotta sofa',
      position: [0, 0, -1.15],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#c96f4f',
    },
    {
      id: 'nook-table',
      asset: 'coffee-table',
      name: 'Walnut coffee table',
      position: [0, 0, -0.35],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#8a5a3b',
    },
    {
      id: 'nook-chair-left',
      asset: 'armchair',
      name: 'Left reading chair',
      position: [-1.35, 0, -0.35],
      rotation: 1.15,
      scale: [1, 1, 1],
      color: '#7f8f7a',
    },
    {
      id: 'nook-chair-right',
      asset: 'armchair',
      name: 'Right reading chair',
      position: [1.35, 0, -0.35],
      rotation: -1.15,
      scale: [1, 1, 1],
      color: '#7f8f7a',
    },
    {
      id: 'nook-shelf',
      asset: 'bookshelf',
      name: 'Corner bookshelf',
      position: [-1.85, 0, -1.55],
      rotation: 0.55,
      scale: [1, 1, 1],
      color: '#5b4636',
    },
    {
      id: 'nook-lamp',
      asset: 'floor-lamp',
      name: 'Brass floor lamp',
      position: [1.65, 0, -1.5],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'nook-plant-left',
      asset: 'plant',
      name: 'Fern by the shelf',
      position: [-1.05, 0, -1.95],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#4f7a4a',
    },
    {
      id: 'nook-plant-right',
      asset: 'plant',
      name: 'Fern by the lamp',
      position: [1.05, 0, -1.95],
      rotation: 0,
      scale: [0.85, 0.85, 0.85],
      color: '#5c8a52',
    },
    {
      id: 'nook-art-center',
      asset: 'art-panel',
      name: 'Cream canvas',
      position: [0, 0, -2.2],
      rotation: 0,
      scale: [1.2, 1, 1],
      color: '#efe3d0',
    },
    {
      id: 'nook-art-left',
      asset: 'art-panel',
      name: 'Small coral study',
      position: [-1.05, 0, -2.2],
      rotation: 0,
      scale: [0.7, 0.7, 1],
      color: '#d97757',
    },
    {
      id: 'nook-art-right',
      asset: 'art-panel',
      name: 'Small sage study',
      position: [1.05, 0, -2.2],
      rotation: 0,
      scale: [0.7, 0.7, 1],
      color: '#8fa38c',
    },
  ],
};

/** Plinths, canvases, and an entry arch, ready for an exhibit model. */
export const GALLERY = {
  title: 'Gallery walk',
  objects: [
    {
      id: 'gallery-arch',
      asset: 'arch',
      name: 'Entry arch',
      position: [0, 0, 0.75],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e7dccb',
    },
    {
      id: 'gallery-plinth-left',
      asset: 'plinth',
      name: 'Left plinth',
      position: [-1.5, 0, -0.9],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-plinth-center',
      asset: 'plinth',
      name: 'Center plinth',
      position: [0, 0, -1.2],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-plinth-right',
      asset: 'plinth',
      name: 'Right plinth',
      position: [1.5, 0, -0.9],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-piece-left',
      asset: 'sphere',
      name: 'Coral sphere',
      position: [-1.5, 0.85, -0.9],
      rotation: 0,
      scale: [0.6, 0.6, 0.6],
      color: '#d97757',
    },
    {
      id: 'gallery-piece-center',
      asset: 'cone',
      name: 'Sage cone',
      position: [0, 0.85, -1.2],
      rotation: 0.4,
      scale: [0.6, 0.7, 0.6],
      color: '#7f8f7a',
    },
    {
      id: 'gallery-piece-right',
      asset: 'box',
      name: 'Slate cube',
      position: [1.5, 0.85, -0.9],
      rotation: 0.6,
      scale: [0.55, 0.55, 0.55],
      color: '#5f6672',
    },
    {
      id: 'gallery-canvas-left',
      asset: 'art-panel',
      name: 'Left canvas',
      position: [-1.7, 0, -2.35],
      rotation: 0.25,
      scale: [1, 1, 1],
      color: '#f3e9da',
    },
    {
      id: 'gallery-canvas-center',
      asset: 'art-panel',
      name: 'Center canvas',
      position: [0, 0, -2.5],
      rotation: 0,
      scale: [1.4, 1.15, 1],
      color: '#c96f4f',
    },
    {
      id: 'gallery-canvas-right',
      asset: 'art-panel',
      name: 'Right canvas',
      position: [1.7, 0, -2.35],
      rotation: -0.25,
      scale: [1, 1, 1],
      color: '#f3e9da',
    },
    {
      id: 'gallery-lamp-left',
      asset: 'floor-lamp',
      name: 'Left gallery lamp',
      position: [-2.3, 0, -1.7],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'gallery-lamp-right',
      asset: 'floor-lamp',
      name: 'Right gallery lamp',
      position: [2.3, 0, -1.7],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'gallery-plant',
      asset: 'plant',
      name: 'Corner planter',
      position: [-2.35, 0, -0.3],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#4f7a4a',
    },
  ],
};

/** A small block of towers, trees, and a gate, readable from above or ahead. */
export const MINIATURE_CITY = {
  title: 'Miniature city',
  objects: [
    {
      id: 'city-base',
      asset: 'box',
      name: 'City model base',
      position: [0, 0, -0.145],
      rotation: 0,
      scale: [2.4, 0.05, 1.75],
      color: '#303840',
    },
    {
      id: 'city-gate',
      asset: 'arch',
      name: 'City gate',
      position: [0, 0.025, 0.225],
      rotation: 0,
      scale: [0.225, 0.225, 0.225],
      color: '#c96f4f',
    },
    {
      id: 'city-tower-a',
      asset: 'building',
      name: 'Cream tower',
      position: [-0.3, 0.025, -0.05],
      rotation: 0,
      scale: [0.275, 0.6, 0.275],
      color: '#e6dccd',
    },
    {
      id: 'city-tower-b',
      asset: 'building',
      name: 'Slate tower',
      position: [-0.1, 0.025, -0.05],
      rotation: 0.1,
      scale: [0.25, 0.4, 0.25],
      color: '#a9b3ba',
    },
    {
      id: 'city-tower-c',
      asset: 'building',
      name: 'Coral tower',
      position: [0.1, 0.025, -0.05],
      rotation: -0.1,
      scale: [0.25, 0.5, 0.25],
      color: '#d97757',
    },
    {
      id: 'city-tower-d',
      asset: 'building',
      name: 'Sand tower',
      position: [0.3, 0.025, -0.05],
      rotation: 0,
      scale: [0.275, 0.325, 0.275],
      color: '#d8c8ac',
    },
    {
      id: 'city-tower-e',
      asset: 'building',
      name: 'Tall cream tower',
      position: [-0.3, 0.025, -0.275],
      rotation: 0,
      scale: [0.3, 0.75, 0.3],
      color: '#efe6d8',
    },
    {
      id: 'city-tower-f',
      asset: 'building',
      name: 'Sage block',
      position: [-0.1, 0.025, -0.275],
      rotation: 0.2,
      scale: [0.25, 0.3, 0.25],
      color: '#7f8f7a',
    },
    {
      id: 'city-tower-g',
      asset: 'building',
      name: 'Center spire',
      position: [0.1, 0.025, -0.275],
      rotation: 0,
      scale: [0.225, 0.9, 0.225],
      color: '#5f6672',
    },
    {
      id: 'city-tower-h',
      asset: 'building',
      name: 'Brick block',
      position: [0.3, 0.025, -0.275],
      rotation: -0.2,
      scale: [0.275, 0.45, 0.275],
      color: '#b5745a',
    },
    {
      id: 'city-tower-i',
      asset: 'building',
      name: 'Back tower',
      position: [-0.2, 0.025, -0.5],
      rotation: 0,
      scale: [0.3, 0.55, 0.3],
      color: '#c9c2b6',
    },
    {
      id: 'city-tower-j',
      asset: 'building',
      name: 'Back spire',
      position: [0.2, 0.025, -0.5],
      rotation: 0.15,
      scale: [0.25, 0.7, 0.25],
      color: '#e6dccd',
    },
    {
      id: 'city-tree-a',
      asset: 'tree',
      name: 'Street tree west',
      position: [-0.45, 0.025, -0.15],
      rotation: 0,
      scale: [0.3, 0.35, 0.3],
      color: '#4f7a4a',
    },
    {
      id: 'city-tree-b',
      asset: 'tree',
      name: 'Street tree east',
      position: [0.45, 0.025, -0.15],
      rotation: 0,
      scale: [0.3, 0.35, 0.3],
      color: '#4f7a4a',
    },
    {
      id: 'city-tree-c',
      asset: 'tree',
      name: 'Park tree',
      position: [0, 0.025, -0.1625],
      rotation: 0,
      scale: [0.25, 0.3, 0.25],
      color: '#5c8a52',
    },
    {
      id: 'city-lamp-west',
      asset: 'floor-lamp',
      name: 'Plaza light west',
      position: [-0.45, 0.025, 0.075],
      rotation: 0,
      scale: [0.15, 0.2, 0.15],
      color: '#e0b872',
    },
    {
      id: 'city-lamp-east',
      asset: 'floor-lamp',
      name: 'Plaza light east',
      position: [0.45, 0.025, 0.075],
      rotation: 0,
      scale: [0.15, 0.2, 0.15],
      color: '#e0b872',
    },
  ],
};

/**
 * One handcrafted compound object, written by hand to show what a grouped
 * moving design looks like. Gemini did not produce it, and it is not a catalog
 * asset: the parts below are ordinary primitives that any live design also
 * uses. Part positions are centers in parent-local meters, sizes are physical
 * meters, and a parent's size never scales its children. The feet rest at
 * y = 0 so the object stands on the scene floor.
 *
 * Four parts carry an authored motion. Positions and rotations stay the rest
 * pose that is saved and exported; motion is local playback around a pivot in
 * the part's own coordinates. The hands are parented to the arms and the eyes
 * and antenna to the head, so they travel with the part that moves them.
 */
export const ROBOT_EXAMPLE = {
  title: 'Clockwork robot',
  objects: [
    {
      id: 'example-robot',
      name: 'Handcrafted clockwork robot',
      position: [0, 0, -0.6],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#ffffff',
      parts: [
        {
          id: 'torso',
          name: 'Torso',
          shape: 'box',
          parent: null,
          position: [0, 0.4, 0],
          rotation: [0, 0, 0],
          size: [0.3, 0.32, 0.2],
          color: '#8fa3b0',
        },
        {
          id: 'chest-panel',
          name: 'Chest panel',
          shape: 'box',
          parent: 'torso',
          position: [0, 0.02, 0.105],
          rotation: [0, 0, 0],
          size: [0.14, 0.12, 0.02],
          color: '#e8714a',
        },
        {
          id: 'neck',
          name: 'Neck',
          shape: 'cylinder',
          parent: 'torso',
          position: [0, 0.185, 0],
          rotation: [0, 0, 0],
          size: [0.07, 0.05, 0.07],
          color: '#5f6672',
        },
        {
          id: 'head',
          name: 'Head',
          shape: 'box',
          parent: 'torso',
          position: [0, 0.31, 0],
          rotation: [0, 0, 0],
          size: [0.22, 0.2, 0.2],
          color: '#c9c2b6',
          motion: {
            kind: 'swing',
            axis: 'y',
            pivot: [0, -0.1, 0],
            amplitude: 0.35,
            period: 6,
          },
        },
        {
          id: 'eye-left',
          name: 'Left eye',
          shape: 'sphere',
          parent: 'head',
          position: [-0.055, 0.02, 0.1],
          rotation: [0, 0, 0],
          size: [0.05, 0.05, 0.03],
          color: '#2b2f36',
        },
        {
          id: 'eye-right',
          name: 'Right eye',
          shape: 'sphere',
          parent: 'head',
          position: [0.055, 0.02, 0.1],
          rotation: [0, 0, 0],
          size: [0.05, 0.05, 0.03],
          color: '#2b2f36',
        },
        {
          id: 'antenna',
          name: 'Antenna',
          shape: 'cylinder',
          parent: 'head',
          position: [0, 0.145, 0],
          rotation: [0, 0, 0],
          size: [0.015, 0.09, 0.015],
          color: '#5f6672',
        },
        {
          id: 'antenna-tip',
          name: 'Antenna tip',
          shape: 'sphere',
          parent: 'antenna',
          position: [0, 0.06, 0],
          rotation: [0, 0, 0],
          size: [0.04, 0.04, 0.04],
          color: '#e8714a',
        },
        {
          id: 'arm-left',
          name: 'Left arm',
          shape: 'capsule',
          parent: 'torso',
          position: [-0.195, 0.02, 0],
          rotation: [0, 0, 0],
          size: [0.07, 0.26, 0.07],
          color: '#7f8f7a',
          motion: {
            kind: 'swing',
            axis: 'x',
            pivot: [0, 0.13, 0],
            amplitude: 0.45,
            period: 2.4,
          },
        },
        {
          id: 'arm-right',
          name: 'Right arm',
          shape: 'capsule',
          parent: 'torso',
          position: [0.195, 0.02, 0],
          rotation: [0, 0, 0],
          size: [0.07, 0.26, 0.07],
          color: '#7f8f7a',
          motion: {
            kind: 'swing',
            axis: 'x',
            pivot: [0, 0.13, 0],
            amplitude: 0.45,
            period: 2.4,
            phase: 0.5,
          },
        },
        {
          id: 'hand-left',
          name: 'Left hand',
          shape: 'sphere',
          parent: 'arm-left',
          position: [0, -0.15, 0],
          rotation: [0, 0, 0],
          size: [0.075, 0.075, 0.075],
          color: '#e0b872',
        },
        {
          id: 'hand-right',
          name: 'Right hand',
          shape: 'sphere',
          parent: 'arm-right',
          position: [0, -0.15, 0],
          rotation: [0, 0, 0],
          size: [0.075, 0.075, 0.075],
          color: '#e0b872',
        },
        {
          id: 'leg-left',
          name: 'Left leg',
          shape: 'cylinder',
          parent: 'torso',
          position: [-0.085, -0.25, 0],
          rotation: [0, 0, 0],
          size: [0.09, 0.18, 0.09],
          color: '#5f6672',
        },
        {
          id: 'leg-right',
          name: 'Right leg',
          shape: 'cylinder',
          parent: 'torso',
          position: [0.085, -0.25, 0],
          rotation: [0, 0, 0],
          size: [0.09, 0.18, 0.09],
          color: '#5f6672',
        },
        {
          id: 'foot-left',
          name: 'Left foot',
          shape: 'box',
          parent: 'leg-left',
          position: [0, -0.12, 0.03],
          rotation: [0, 0, 0],
          size: [0.11, 0.06, 0.18],
          color: '#3f454d',
        },
        {
          id: 'foot-right',
          name: 'Right foot',
          shape: 'box',
          parent: 'leg-right',
          position: [0, -0.12, 0.03],
          rotation: [0, 0, 0],
          size: [0.11, 0.06, 0.18],
          color: '#3f454d',
        },
        {
          id: 'wind-key',
          name: 'Wind-up key',
          shape: 'box',
          parent: 'torso',
          position: [0, 0.02, -0.12],
          rotation: [0, 0, 0],
          size: [0.13, 0.026, 0.06],
          color: '#e0b872',
          motion: {
            kind: 'spin',
            axis: 'z',
            pivot: [0, 0, 0],
            speed: 2.4,
          },
        },
      ],
    },
  ],
};

/**
 * One handcrafted virtual setting, written by hand to show what the landscape
 * recipes look like. Gemini did not produce it, and it is not a preset that a
 * request can select. The environment owns a 14 by 14 meter ground, a sky, and
 * its lighting, all generated locally from the four fields below.
 *
 * Water, walkways, and planting are compact recipes rather than hundreds of
 * saved objects: one scatter is a single selectable feature holding a style, a
 * planting area, a specimen count, a seed, and a maximum height. The seeds are
 * fixed here so this example draws the same arrangement every time. The bridge,
 * pavilion, and lantern are ordinary procedural parts, because authored
 * structures are not landscape features.
 */
export const MOONLIT_GARDEN = {
  title: 'Moonlit garden',
  environment: {
    size: [14, 14],
    groundColor: '#3f4a3a',
    timeOfDay: 'moonlight',
  },
  objects: [
    {
      id: 'garden-pond',
      name: 'Reflecting pond',
      landscape: {kind: 'pond', size: [4.4, 2.8], bankWidth: 0.35},
      position: [-2.2, 0, 0.6],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#33566b',
    },
    {
      id: 'garden-path',
      name: 'Winding gravel path',
      landscape: {
        kind: 'path',
        points: [
          [0, 6],
          [0.2, 4.2],
          [1.4, 2.8],
          [1.6, 1],
          [0.6, -0.6],
          [-1.2, -1.6],
          [-2.6, -3],
        ],
        width: 0.9,
      },
      position: [0, 0, 0],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#8d8577',
    },
    {
      id: 'garden-trees-north',
      name: 'Maples along the far edge',
      landscape: {
        kind: 'scatter',
        style: 'tree',
        size: [10, 3.6],
        count: 12,
        seed: 4127,
        height: 3.4,
      },
      position: [-1.6, 0, -4.6],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#41603f',
    },
    {
      id: 'garden-trees-west',
      name: 'Maples beside the water',
      landscape: {
        kind: 'scatter',
        style: 'tree',
        size: [2.6, 8],
        count: 7,
        seed: 6619,
        height: 3,
      },
      position: [-5.4, 0, 1.6],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#4a6a44',
    },
    {
      id: 'garden-shrubs',
      name: 'Clipped shrubs by the pavilion',
      landscape: {
        kind: 'scatter',
        style: 'shrub',
        size: [4.5, 4],
        count: 14,
        seed: 1187,
        height: 0.75,
      },
      position: [2.8, 0, 1.8],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#4d6b45',
    },
    {
      id: 'garden-rocks',
      name: 'Stones along the bank',
      landscape: {
        kind: 'scatter',
        style: 'rock',
        size: [6, 2.2],
        count: 9,
        seed: 733,
        height: 0.5,
      },
      position: [-2.4, 0, 2.6],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#6f6a63',
    },
    {
      id: 'garden-grass',
      name: 'Grass near the entrance',
      landscape: {
        kind: 'scatter',
        style: 'grass',
        size: [11, 4],
        count: 36,
        seed: 5209,
        height: 0.3,
      },
      position: [0, 0, 3.6],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#5c7a4e',
    },
    {
      id: 'garden-flowers',
      name: 'Iris bed',
      landscape: {
        kind: 'scatter',
        style: 'flower',
        size: [3.4, 2.4],
        count: 18,
        seed: 8803,
        height: 0.32,
      },
      position: [3.4, 0, 3.4],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#b47ab0',
    },
    {
      id: 'garden-bridge',
      name: 'Plank bridge over the pond',
      position: [-0.55, 0, 0.6],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#ffffff',
      parts: [
        {
          id: 'deck',
          name: 'Deck',
          shape: 'box',
          parent: null,
          position: [0, 0.36, 0],
          rotation: [0, 0, 0],
          size: [1.1, 0.08, 3.2],
          color: '#7a5236',
        },
        {
          id: 'rail-left',
          name: 'Left rail',
          shape: 'cylinder',
          parent: 'deck',
          position: [-0.5, 0.4, 0],
          rotation: [Math.PI / 2, 0, 0],
          size: [0.06, 3, 0.06],
          color: '#8a6040',
        },
        {
          id: 'rail-right',
          name: 'Right rail',
          shape: 'cylinder',
          parent: 'deck',
          position: [0.5, 0.4, 0],
          rotation: [Math.PI / 2, 0, 0],
          size: [0.06, 3, 0.06],
          color: '#8a6040',
        },
        {
          id: 'post-north-left',
          name: 'Far left post',
          shape: 'box',
          parent: 'deck',
          position: [-0.5, 0.2, -1.4],
          rotation: [0, 0, 0],
          size: [0.09, 0.48, 0.09],
          color: '#6b4a30',
        },
        {
          id: 'post-north-right',
          name: 'Far right post',
          shape: 'box',
          parent: 'deck',
          position: [0.5, 0.2, -1.4],
          rotation: [0, 0, 0],
          size: [0.09, 0.48, 0.09],
          color: '#6b4a30',
        },
        {
          id: 'post-south-left',
          name: 'Near left post',
          shape: 'box',
          parent: 'deck',
          position: [-0.5, 0.2, 1.4],
          rotation: [0, 0, 0],
          size: [0.09, 0.48, 0.09],
          color: '#6b4a30',
        },
        {
          id: 'post-south-right',
          name: 'Near right post',
          shape: 'box',
          parent: 'deck',
          position: [0.5, 0.2, 1.4],
          rotation: [0, 0, 0],
          size: [0.09, 0.48, 0.09],
          color: '#6b4a30',
        },
      ],
    },
    {
      id: 'garden-pavilion',
      name: 'Small pavilion',
      position: [3.2, 0, -1.6],
      rotation: -0.35,
      scale: [1, 1, 1],
      color: '#ffffff',
      parts: [
        {
          id: 'platform',
          name: 'Platform',
          shape: 'box',
          parent: null,
          position: [0, 0.12, 0],
          rotation: [0, 0, 0],
          size: [2.2, 0.24, 2.2],
          color: '#7d5a3c',
        },
        {
          id: 'post-a',
          name: 'Front left post',
          shape: 'cylinder',
          parent: 'platform',
          position: [-0.85, 1.06, 0.85],
          rotation: [0, 0, 0],
          size: [0.12, 1.8, 0.12],
          color: '#5f4128',
        },
        {
          id: 'post-b',
          name: 'Front right post',
          shape: 'cylinder',
          parent: 'platform',
          position: [0.85, 1.06, 0.85],
          rotation: [0, 0, 0],
          size: [0.12, 1.8, 0.12],
          color: '#5f4128',
        },
        {
          id: 'post-c',
          name: 'Back left post',
          shape: 'cylinder',
          parent: 'platform',
          position: [-0.85, 1.06, -0.85],
          rotation: [0, 0, 0],
          size: [0.12, 1.8, 0.12],
          color: '#5f4128',
        },
        {
          id: 'post-d',
          name: 'Back right post',
          shape: 'cylinder',
          parent: 'platform',
          position: [0.85, 1.06, -0.85],
          rotation: [0, 0, 0],
          size: [0.12, 1.8, 0.12],
          color: '#5f4128',
        },
        {
          id: 'roof',
          name: 'Roof',
          shape: 'cone',
          parent: 'platform',
          position: [0, 2.36, 0],
          rotation: [0, Math.PI / 4, 0],
          size: [3.1, 0.8, 3.1],
          color: '#3f3a41',
        },
      ],
    },
    {
      id: 'garden-lantern',
      name: 'Stone lantern',
      position: [1.05, 0, 2.6],
      rotation: 0.4,
      scale: [1, 1, 1],
      color: '#ffffff',
      parts: [
        {
          id: 'base',
          name: 'Base',
          shape: 'cylinder',
          parent: null,
          position: [0, 0.09, 0],
          rotation: [0, 0, 0],
          size: [0.44, 0.18, 0.44],
          color: '#8a857c',
        },
        {
          id: 'column',
          name: 'Column',
          shape: 'cylinder',
          parent: 'base',
          position: [0, 0.38, 0],
          rotation: [0, 0, 0],
          size: [0.18, 0.58, 0.18],
          color: '#8a857c',
        },
        {
          id: 'lamp',
          name: 'Lamp housing',
          shape: 'box',
          parent: 'column',
          position: [0, 0.44, 0],
          rotation: [0, 0.35, 0],
          size: [0.36, 0.3, 0.36],
          color: '#cfc6ae',
        },
        {
          id: 'cap',
          name: 'Cap',
          shape: 'cone',
          parent: 'lamp',
          position: [0, 0.26, 0],
          rotation: [0, 0, 0],
          size: [0.52, 0.22, 0.52],
          color: '#7c776f',
        },
      ],
    },
  ],
};

/** The starter scenes offered in the demo, in the order they are shown. */
export const STARTER_SCENES = [
  {
    id: 'reading-nook',
    label: 'Reading nook',
    summary: 'A sofa, two chairs, a shelf, and framed art.',
    layout: READING_NOOK,
  },
  {
    id: 'gallery',
    label: 'Gallery',
    summary: 'Plinths, canvases, and an entry arch.',
    layout: GALLERY,
  },
  {
    id: 'miniature-city',
    label: 'Miniature city',
    summary: 'A block of towers, trees, and a gate.',
    layout: MINIATURE_CITY,
  },
  {
    id: 'robot-example',
    label: 'Clockwork robot',
    summary:
      'One handcrafted compound object of 17 primitive parts with authored swing and spin motion, not AI output.',
    layout: ROBOT_EXAMPLE,
  },
];

/**
 * The starter scenes offered in the virtual-world mode. The default page keeps
 * its own list, so this example never replaces a room-scale starter scene.
 */
export const ENVIRONMENT_STARTER_SCENES = [
  {
    id: 'moonlit-garden',
    label: 'Moonlit garden',
    summary:
      'One handcrafted virtual setting with a pond, a path, six seeded planting areas, and three part-based structures, not AI output.',
    layout: MOONLIT_GARDEN,
  },
];
