/** Configuration array defining all available animal models. */
export const ANIMAL_MODELS = [
  {
    name: 'Dog',
    path: 'https://cdn.jsdelivr.net/gh/Geo-Web-Project/webxr-experiments@main/',
    file: 'shiba.glb',
    scale: 0.55,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Dog/3D/dog_3d.png',
  },
  {
    name: 'Flamingo',
    path: 'https://cdn.jsdelivr.net/gh/mrdoob/three.js@r160/examples/models/gltf/',
    file: 'Flamingo.glb',
    scale: 0.06,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Flamingo/3D/flamingo_3d.png',
  },
  {
    name: 'Parrot',
    path: 'https://cdn.jsdelivr.net/gh/mrdoob/three.js@r160/examples/models/gltf/',
    file: 'Parrot.glb',
    scale: 0.06,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Parrot/3D/parrot_3d.png',
  },
  {
    name: 'Horse',
    path: 'https://cdn.jsdelivr.net/gh/mrdoob/three.js@r160/examples/models/gltf/',
    file: 'Horse.glb',
    scale: 0.06,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Horse/3D/horse_3d.png',
  },
  {
    name: 'Stork',
    path: 'https://cdn.jsdelivr.net/gh/mrdoob/three.js@r160/examples/models/gltf/',
    file: 'Stork.glb',
    scale: 0.06,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Swan/3D/swan_3d.png',
  },
  {
    name: 'Duck',
    path: 'https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Models@master/2.0/Duck/glTF-Binary/',
    file: 'Duck.glb',
    scale: 0.45,
    rotY: -90,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Duck/3D/duck_3d.png',
  },
  {
    name: 'Cat',
    path: 'https://cdn.jsdelivr.net/gh/xrblocks/assets@main/models/Cat/',
    file: 'cat.gltf',
    scale: 1.0,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Cat/3D/cat_3d.png',
  },
  {
    name: 'Dinosaur',
    path: 'https://cdn.jsdelivr.net/gh/xrblocks/assets@main/models/',
    file: 'Parasaurolophus.glb',
    scale: 0.3,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Sauropod/3D/sauropod_3d.png',
  },
  {
    name: 'Robot',
    path: 'https://cdn.jsdelivr.net/gh/mrdoob/three.js@r160/examples/models/gltf/RobotExpressive/',
    file: 'RobotExpressive.glb',
    scale: 0.3,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Robot/3D/robot_3d.png',
  },
  {
    name: 'Fish',
    path: 'https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Models@master/2.0/BarramundiFish/glTF-Binary/',
    file: 'BarramundiFish.glb',
    scale: 1.0,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Fish/3D/fish_3d.png',
  },
  {
    name: 'Runner',
    path: 'https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Models@master/2.0/CesiumMan/glTF-Binary/',
    file: 'CesiumMan.glb',
    scale: 0.6,
    rotY: 0,
    img: 'https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Alien/3D/alien_3d.png',
  },
];
