name: Create build branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v4
      - name: Checkout repo-B (the other private repo)
        uses: actions/checkout@v4
        with:
          repository: google/xrblocks
          ssh-key: ${{ secrets.READ_XRBLOCKS_SSH_KEY }}
          path: ./xrblocks
      - name: Setup Node.js for xrblocks
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './xrblocks/package-lock.json'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./xrblocks
      - name: Build Project
        run: npm run build
        working-directory: ./xrblocks
      - name: Copy out build
        run : mv ./xrblocks/build ./build/
      - name: Setup Node.js for docs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './xrblocks/docs/package-lock.json'
      - name: Install Docs Dependencies
        run: npm ci
        working-directory: ./xrblocks/docs
      - name: Build Docs
        run: npm run build
        working-directory: ./xrblocks/docs
        env:
            XRBLOCKS_BASE_URL: https://xrblocks.github.io/
      - name: Copy out docs
        run : mv ./xrblocks/docs/build/ ./build/docs
      - name: Copy out demos
        run : mv ./xrblocks/demos ./build/
      - name: Copy out samples
        run : mv ./xrblocks/samples ./build/
      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # Set the target branch to 'build'
          publish_branch: build